import { launch, login, BASE } from './lib.mjs'
const b = await launch()
const p = await b.newPage()
await login(p, 'finance@avenue.co.ke')
await p.goto(BASE + '/settlement', { waitUntil: 'networkidle2' })
await new Promise(r => setTimeout(r, 2000))
let t = await p.evaluate(() => document.body.innerText.replace(/\s+/g, ' '))
console.log('finance sees settlement page:', t.slice(0, 150))
await p.evaluate(() => { [...document.querySelectorAll('button')].find(x => x.offsetParent && /^approve$/i.test(x.innerText.trim()))?.click() })
await new Promise(r => setTimeout(r, 5000))
t = await p.evaluate(() => document.body.innerText.replace(/\s+/g, ' '))
console.log('after approve:', t.slice(0, 130))
await p.goto(BASE + '/settlement', { waitUntil: 'networkidle2' })
await new Promise(r => setTimeout(r, 2000))
t = await p.evaluate(() => document.body.innerText.replace(/\s+/g, ' '))
const i = t.indexOf('All (')
console.log('STATE:', t.slice(i, i + 350))
await p.screenshot({ path: 'C:/Coding/avenue-portal/uat/screenshots/9.5-checker.png' })
await b.close()
console.log('DONE')
