import { launch, login, BASE } from './lib.mjs'
const b = await launch()
const p = await b.newPage()
await login(p, 'finance@avenue.co.ke')
await p.goto(BASE + '/settlement', { waitUntil: 'networkidle2' })
await new Promise(r => setTimeout(r, 2000))
await p.evaluate(() => { [...document.querySelectorAll('button')].find(x => x.offsetParent && /^paid$|mark paid/i.test(x.innerText.trim()))?.click() })
await new Promise(r => setTimeout(r, 5000))
await p.goto(BASE + '/settlement', { waitUntil: 'networkidle2' })
await new Promise(r => setTimeout(r, 2000))
const t = await p.evaluate(() => document.body.innerText.replace(/\s+/g, ' '))
const i = t.indexOf('All (')
console.log('FINAL:', t.slice(i, i + 300))
await p.screenshot({ path: 'C:/Coding/avenue-portal/uat/screenshots/9.5-paid.png' })
await b.close()
console.log('DONE')
