import { launch, login, BASE } from './lib.mjs'
const b = await launch()
const p = await b.newPage()
await login(p, 'finance@avenue.co.ke')
await p.goto(BASE + '/settlement', { waitUntil: 'networkidle2' })
await new Promise(r => setTimeout(r, 2000))
await p.evaluate(() => { [...document.querySelectorAll('button')].find(x => x.offsetParent && /paid/i.test(x.innerText.trim()))?.click() })
await new Promise(r => setTimeout(r, 2500))
await p.screenshot({ path: 'C:/Coding/avenue-portal/uat/screenshots/9.5-paid-dialog.png' })
const els = await p.evaluate(() => [...document.querySelectorAll('input,textarea,button')].filter(x => x.offsetParent).map(x => ({ tag: x.tag, t: (x.innerText || x.placeholder || '').trim().slice(0, 35) })).filter(x => x.t && !/OVERVIEW|FINANCE|INSIGHTS|Log out|Dashboard/.test(x.t)))
console.log('after paid click:', JSON.stringify(els))
console.log('page:', (await p.evaluate(() => document.body.innerText.replace(/\s+/g, ' '))).slice(0, 200))
await b.close()
console.log('DONE')
